/**
 * Consolidação de posts canibais — 25/08/2026.
 *
 * A auditoria encontrou 4 aglomerados de posts disputando a mesma intenção de
 * busca. Dois deles concentravam 80 posts sobre "habilidades do desenvolvedor",
 * assunto que não atrai o público que a Dexi vende (grupo automotivo, clínica,
 * incorporadora). Com 80 páginas na mesma consulta, nenhuma acumula autoridade
 * e o buscador escolhe uma quase ao acaso.
 *
 * Cada aglomerado virou um post canônico; o resto redireciona com 301 para ele.
 * Nenhuma URL retorna 404 — quem tinha link continua chegando em conteúdo vivo,
 * e a autoridade dos 83 endereços se concentra em 4.
 *
 * PARA REVERTER: apague este arquivo, remova o import em next.config.ts e
 * restaure lib/blog-data.ts do histórico do git. Nada foi perdido.
 *
 * O canônico foi escolhido por profundidade de conteúdo e data, porque não há
 * Search Console conectado. Com dados de tráfego, vale reconferir se o canônico
 * escolhido é mesmo o que tinha posição — e trocar o destino, se não for.
 */
export const BLOG_REDIRECTS: [origem: string, destino: string][] = [
  ['7-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['abracando-a-ia-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['adapte-se-inovem-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedor-supere-desafios-2024-2025-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-se-preparar-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-10', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-11', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-3', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-4', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-5', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-6', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-7', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-8', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-2025-9', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-destacar-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-podem-superar-desafios-2024-em-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025-3', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025-4', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025-5', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-2025-6', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2024-preparados-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-desenvolvedores-superar-desafios-prosperar', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['como-superar-desafios-2024-dominar-2025-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['conquiste-2025-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desafios-2024-tendencias-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desbravando-desafios-2024-estrategias-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedor-habilidades-essenciais-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedor-habilidades-essenciais-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-de-2025-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-desafios-2024-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-em-2025-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-habilidades-essenciais-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-habilidades-essenciais-2025-3', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-precisam-dominar-2025-desafios-2024', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-prepare-se-para-2025-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['desenvolvedores-principais-habilidades-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['dominar-habilidades-essenciais-desenvolvedor-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['dominar-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['dominar-habilidades-essenciais-desenvolvedores-2025-ia', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['domine-2025-7-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['domine-2025-como-desenvolvedores-superarao-desafios-2024', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['domine-2025-desafios-developers-2024', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['domine-competencias-essenciais-desenvolvedor-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['domine-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['enfrente-desafios-2024-prepare-futuro-2025-7-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['escassez-de-talentos-tech-solucao', 'staff-augmentation-tech-solucao-escassez'],
  ['escassez-de-talentos-tech-staff-augmentation', 'staff-augmentation-tech-solucao-escassez'],
  ['estrategias-2025-desenvolvedores-superar-desafios-2024', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['fique-pronto-futuro-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedor-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-3', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-4', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-6', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-7', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['habilidades-essenciais-desenvolvedores-2025-8', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['prepare-para-2025-7-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['prepare-para-os-desafios-de-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['prepare-para-prosperar-em-2025-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['principais-habilidades-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['quais-sao-as-tendencias-para-2024-no-desenvolvimento-do-ecossistema-de-saude-de-acordo-com-a-dexi-digital', 'quais-sao-as-tendencias-de-desenvolvimento-movel-para-2024-de-acordo-com-a-dexi-digital'],
  ['quais-sao-as-tendencias-tecnologicas-para-2024-de-acordo-com-a-dexi-digital', 'quais-sao-as-tendencias-de-desenvolvimento-movel-para-2024-de-acordo-com-a-dexi-digital'],
  ['sete-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-2024-prospere-2025-habilidades-desenvolvimento', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-desafios-2024-7-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-desafios-2024-impulsione-negocios-2025-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-2024-2025-desenvolvedores-prosperarem', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-2024-2025-developers-ia-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-2024-7-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-2024-7-habilidades-essenciais-desenvolvedores-2025-2', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-2024-prospere-2025-habilidades-essenciais-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-com-as-7-habilidades-essenciais-para-desenvolvedores-em-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-com-estas-7-habilidades-essenciais-para-desenvolvedores-em-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-com-habilidades-essenciais-desenvolvedores-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-com-habilidades-essenciais-para-desenvolvedores', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-e-se-prepare-para-2025-7-habilidades-essenciais', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
  ['supere-os-desafios-de-2024-impulsione-a-inovacao-em-2025', 'descubra-7-habilidades-essenciais-desenvolvedores-2025-3'],
];
